[package]
name = "li-sim"
version = "0.1.0"
edition = "2026"
license = "Apache-2.0 OR MIT"
description = "Li package li-sim"

[dependencies]
# path = { path = "../other" }   # lip 8b+
# registry = "1.0.0"             # lip 8d+

[package.metadata.li]
github_repo = "li-sim"
import_name = "sim"
min_lic = "0.1.0"



[package.repository]
url = "https://github.com/li-langverse/li-sim"
documentation = "https://li-langverse.github.io/li-language/ecosystem/li-sim/"
changelog = "https://github.com/li-langverse/li-sim/blob/main/CHANGELOG.md"
